function averaging_subject(sFiles)
    bst_process('CallProcess', 'process_average', sFiles, [], ...
        'avgtype',       2, ...  % By subject
        'avg_func',      1, ...  % Arithmetic average:  mean(x)
        'weighted',      0, ...
        'matchrows',     1, ...
        'iszerobad',     1);
end