function domain_average(sFiles, name)
    sFiles = bst_process('CallProcess', 'process_average', sFiles, [], ...
        'avgtype',       1, ...  % Everything
        'avg_func',      1, ...  % Arithmetic average:  mean(x)
        'weighted',      0, ...
        'matchrows',     1, ...
        'iszerobad',     1);
    
    bst_process('CallProcess', 'process_set_comment', sFiles, [], ...
        'tag',           name, ...
        'isindex',       0);
