function timefreq_analysis(sFiles)
    bst_process('CallProcess', 'process_timefreq', sFiles, [], ...
        'sensortypes',   'MEG, EEG', ...
        'edit',          struct(...
             'Comment',         'Power,TimeBands,FreqBands', ...
             'TimeBands',       {{'all', '0.000, 2.996', 'mean'}}, ...
             'Freqs',           {{'delta', '2, 4', 'mean'; 'theta', '4, 8', 'mean'; 'alpha', '8, 12', 'mean'; 'beta', '15, 30', 'mean'; 'gamma', '30, 45', 'mean'}}, ...
             'MorletFc',        1, ...
             'MorletFwhmTc',    3, ...
             'ClusterFuncTime', 'none', ...
             'Measure',         'power', ...
             'Output',          'all', ...
             'RemoveEvoked',    0, ...
             'SaveKernel',      0), ...
        'normalize2020', 0, ...
        'normalize',     'none');  % None: Save non-standardized time-frequency maps
end
