% Script generated by Brainstorm (21-Jun-2023)

% Input files
sFiles = {...
    '1-Receptivity/TIMAH_ANI1_PRE_S07_RosmainitaSari_01/timefreq_average_230724_1032.mat', ...
    '1-Receptivity/TIMAH_ANI1_PRE_S07_RosmainitaSari_02/timefreq_average_230724_1032.mat'};

% Start a new report
bst_report('Start', sFiles);

% Process: Average: Everything
sFiles = bst_process('CallProcess', 'process_average', sFiles, [], ...
    'avgtype',       1, ...  % Everything
    'avg_func',      1, ...  % Arithmetic average:  mean(x)
    'weighted',      0, ...
    'matchrows',     1, ...
    'iszerobad',     1);

% Save and display report
ReportFile = bst_report('Save', sFiles);
bst_report('Open', ReportFile);
% bst_report('Export', ReportFile, ExportDir);
% bst_report('Email', ReportFile, username, to, subject, isFullReport);

% Delete temporary files
% gui_brainstorm('EmptyTempFolder');

